name: Test and check code

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Python tests and checks
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - run: pip install --upgrade pip
    - run: pip install "black<23" pylint pytest
    - run: pip install -r image/requirements.txt
    - run: black --diff --check $(git ls-files '*.py')
    - run: pylint --fail-under=8.5 $(git ls-files '*.py')
    - run: pytest
